# Practice With Numpy Dimensions

In this notebook, I wish to understand the fundamentals of how numpy array's are dimensioned and sliced. I would like to create reproducible results where I can slice and dice through a multi dimensional array conclusively

In [1]:
import numpy as np
import pandas as pd

Here I define the problem statement as follows. I have four points in 3D space, with coordinates (x, y, z). I would like to convert these to a numpy array and compute the maximum distance between them. 

We define our dictionary of points `p1`, `p2`, `p3`, and `p4` with coordinates as follows.

In [8]:
points_dict = {
    'p1': [1,8,55],
    'p2': [2,13,89],
    'p3': [3,21,34],
    'p4': [5,34,233]
}

print(points_dict)

{'p1': [1, 8, 55], 'p2': [2, 13, 89], 'p3': [3, 21, 34], 'p4': [5, 34, 233]}


We create our numpy arrays as follows.

In [3]:
x = np.array([1,2,3,5])
y = np.array([8,13,21,34])
z = np.array([55,89,144,233])

Concatenate our 3, 1D vectors as follows.

In [4]:
dx_vec = x[:, None] - x[None, :]
dx_vec

array([[ 0, -1, -2, -4],
       [ 1,  0, -1, -3],
       [ 2,  1,  0, -2],
       [ 4,  3,  2,  0]])

In [5]:
dy_vec = y[:, None] - y[None, :]
dy_vec

array([[  0,  -5, -13, -26],
       [  5,   0,  -8, -21],
       [ 13,   8,   0, -13],
       [ 26,  21,  13,   0]])

In [6]:
dz_vec = z[:, None] - z[None, :]
dz_vec

array([[   0,  -34,  -89, -178],
       [  34,    0,  -55, -144],
       [  89,   55,    0,  -89],
       [ 178,  144,   89,    0]])

Now we have our three distance vectors, we can square them , sum them up, and take the results' square root to get the individual distance.

In [14]:
D_vec = np.sqrt(np.square(dx_vec) + np.square(dy_vec) + np.square(dz_vec))
D_vec

array([[  0.        ,  34.38022688,  89.96666049, 179.93332098],
       [ 34.38022688,   0.        ,  55.58776844, 145.55411365],
       [ 89.96666049,  55.58776844,   0.        ,  89.96666049],
       [179.93332098, 145.55411365,  89.96666049,   0.        ]])

In [ ]:
np.max(D_vec)

In [11]:
np.argmax(D_vec)

np.int64(3)

In [19]:
D_vec[[0,3]]

array([[  0.        ,  34.38022688,  89.96666049, 179.93332098],
       [179.93332098, 145.55411365,  89.96666049,   0.        ]])

In [20]:
test_array = np.array([[1,2,3,4],
                       [5,6,7,8],
                       [9,10,11,12]])
test_array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [27]:
test_array[[0,2]]

array([[ 1,  2,  3,  4],
       [ 9, 10, 11, 12]])

Slicing like this appears to select the individual rows. If I want rows 0 and 2, this is how you'd do it. `[[0,2]]`

In [ ]:
test_array[0][2]

np.int64(5)

In [ ]:
test_face = (87, 17, 18, 84)
test_face

In [ ]:
""" 
Testing area

"""

i, j, k, h = test_face

mapping_dict = {
    0 : i,
    1 : j,
    2 : k,
    3 : h
}

print(i,j,k,h)

x = np.array(vertices_new.loc[[i,j,k,h], 'X'].values)
y = np.array(vertices_new.loc[[i,j,k,h], 'Y'].values)
z = np.array(vertices_new.loc[[i,j,k,h], 'Z'].values)

dx_vec = x[:, None] - x[None, :]
dy_vec = y[:, None] - y[None, :]
dz_vec = z[:, None] - z[None, :]

D_vec = np.sqrt(np.square(dx_vec) + np.square(dy_vec) + np.square(dz_vec))

print(D_vec)

p1 = np.argmax(D_vec) // 4
p2 = np.argmax(D_vec) % 4

print(p1, p2)
print(D_vec[p1][p2])

print(mapping_dict[p1], mapping_dict[p2])

""" 
End Testing area
"""